language: python
python:
- 3.5
install:
- pip install tox-travis
- pip install coverage==5.1
- pip install django
- pip install django_coverage_plugin
- pip install coveralls==2.0.0
- pip install python-coveralls

script:
- tox
notifications:
  slack:
    rooms:
      secure: kQ7lXeRJKGVLooAhv+PjYMf18R/zVUNVzYNj7o6DdQi9/7a6J7N2b/QJrHQ690ZBv/PbXhnN6H8hlb9GkpnGmxzTlUz+H4FBvSixQvEW3oB0thBhZrpjpzTMavhXKRrIeq8Uo8Uamo99HiuDPgiul9oTbq53stSq/FUtqKei7DaP00swMbOnYf8IlJpTTuVvEBGZ4yiGkxcxNwb46Qndv/Hypqpy5tNG85BhYfy/0zZd47vKkRxbwT+BA9g7U5Hz7HrFEnvCqAoVgbV+uxxOL8pESKdg/6lcLRl6e348SCXT4G+cvki3sgNj9mRXblTK6bNIP5PG/yO+6E6YhP7lkqjQ9536meVpZMURUahaAb9e1GKLBWYPobWcmdAjIcuIe3OxISuo2aA2izixOncE8lJb7py5XPSrqBcX5+h/X0DlzDmh26pMgPlPuCDfNe8QIV98KFdXQ6XxNBOZBJe9U32E933SBtlMYE+nJW8dAt+9w3y+dW6aAUo6z9VFUXVpfejo9rielPJE1kOcIsNrgj6RrtT6qKNg7uCs25sZZfJKMyN8rHXa+9IClMf2Ct8LLLOAf1Q8IbNubt9xuDzQdg5rJqY8zAVZCdIe08oR5xEc1lMKmjFQH7B+j5yKxlBNIlyWwFqfTZtgEXOQOu2MByDLpd/lwwxsR5BO7Hmt9G0=
    on_success: change
    on_failure: always
after_success:
 - COVERALLS_REPO_TOKEN="$COVERALLS_REPO_TOKEN" coveralls
